version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - wordpress
    volumes:
      - 'volumes_wordpress:/var/www/html'
    ports:
      - '443:443'
    networks:
      - intra
    env_file:
      - .env
    restart: always

  wordpress:
    # Dockerfile이 있는 위치
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    volumes:
      - 'volumes_wordpress:/var/www/html'
    networks:
      - intra
    env_file:
      - .env
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    networks:
      - intra
    env_file:
      - .env
    restart: always

volumes:
  volumes_wordpress:
    driver_opts:
      type: 'bind'
      device: ':$HOME/kipark/data/'

networks:
  intra:
    driver: bridge
