# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kipark <kipark@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/14 16:11:13 by kipark            #+#    #+#              #
#    Updated: 2022/01/15 23:30:35 by kipark           ###   ########seoul.kr   #
#                                                                              #
# **************************************************************************** #

CC 		= gcc
CC_FLAG = -Wextra -Werror -Wall -g

src = 	get_next_line.c			\
		get_next_line_utils.c	\
		get_next_line.h \
		main.c

src_b = get_next_line_bonus.c			\
		get_next_line_utils_bonus.c			\
		get_next_line_bonus.h 				\
		main.c

all :
	$(CC) $(CC_FLAG) $(src)

b	:
	$(CC) $(CC_FLAG) $(src_b)