# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kipark <kipark@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/14 16:11:13 by kipark            #+#    #+#              #
#    Updated: 2021/12/14 16:15:53 by kipark           ###   ########seoul.kr   #
#                                                                              #
# **************************************************************************** #

CC 		= gcc
CC_FLAG = -Wextra -Werror -Wall

src = 	get_next_line.c			\
		get_next_line_utils.c	\
		main.c	

all :
	$(CC) $(CC_FLAG) $(src)